#!/usr/bin/with-contenv bash

# install Mcrypt
apk add --update php5-mcrypt

RUN apk upgrade --update && apk add \
  coreutils \
  libmcrypt-dev \
  php5-mcrypt \
## install mcrypt
  && docker-php-ext-configure mcrypt \
  --with-mcrypt \
  && docker-php-ext-install  mcrypt \
  && apk del \
  libmcrypt-dev \
	
# fetch site
[[ ! -d /config/www/phlex/.git ]] && \
	git clone https://github.com/d8ahazard/Phlex /config/www/Phlex

# permissions
chown -R abc:abc \
	/config/www
