#!/usr/bin/with-contenv bash

apk update && \
apk upgrade && apk add --update libressl libressl-dev libssl1.0 \
	coreutils \
	libmcrypt-dev \
	php7 \
	php7-fpm \
	php7-phar \
	php7-openssl \
	php7-common \
	php7-dev \
	apk add --no-cache \
 	--repository http://nl.alpinelinux.org/alpine/edge/community \
	php7-json \
	php7-curl \
	php7-mcrypt \
	php7-sockets \
	php7-xml && \
	
# fetch site
[[ ! -d /config/www/phlex/.git ]] && \
	git clone https://github.com/d8ahazard/Phlex /config/www/Phlex


cd /config/www/Phlex
git pull

# permissions
chown -R abc:abc \
	/config/www	
	

